server:
  port: 8080
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /info
    healthCheckUrlPath: /health


logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG
zuul:
#  strip-prefix: true This would result to http://localhost:8080/api/webapp/webapp/one
#  prefix: /api
